// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'bottomLeft': string;
  'bottomRight': string;
  'fadeAppear': string;
  'fadeAppearActive': string;
  'fadeAppearDone': string;
  'fadeEnter': string;
  'fadeEnterActive': string;
  'fadeEnterDone': string;
  'fadeExit': string;
  'fadeExitActive': string;
  'fader': string;
  'icons': string;
  'image': string;
  'instruction': string;
  'instructions': string;
  'keyboard': string;
  'media': string;
  'preamble': string;
  'slidein': string;
  'start': string;
  'text': string;
  'textFrame': string;
  'topLeft': string;
  'topRight': string;
}
export const cssExports: CssExports;
export default cssExports;
