// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'beat': string;
  'bottom': string;
  'club': string;
  'fadeAppear': string;
  'fadeAppearActive': string;
  'fadeAppearDone': string;
  'fadeEnter': string;
  'fadeEnterActive': string;
  'fadeEnterDone': string;
  'fadeExit': string;
  'fadeExitActive': string;
  'fader': string;
  'icons': string;
  'image': string;
  'instruction': string;
  'instructions': string;
  'keyboard': string;
  'left': string;
  'media': string;
  'preamble': string;
  'pulse0': string;
  'pulse1': string;
  'pulse2': string;
  'pulse3': string;
  'right': string;
  'slidein': string;
  'start': string;
  'text': string;
  'textFrame': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
