// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'face': string;
  'textWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
